# Generated by Django 3.2.6 on 2021-08-20 14:02

import app_saver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.ImageField(upload_to=app_saver.models.get_image_path)),
                ('size', models.ImageField(blank=True, null=True, upload_to='')),
                ('saved_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnsplashDailyLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('loaded_images', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
