# Generated by Django 3.2.6 on 2021-08-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_saver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedimage',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
