# Generated by Django 3.2.6 on 2021-08-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_saver', '0002_alter_savedimage_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
