# Generated by Django 3.2.6 on 2021-08-24 07:44

import app_saver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_saver', '0003_savedimage_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedimage',
            old_name='image',
            new_name='full_image',
        ),
        migrations.AddField(
            model_name='savedimage',
            name='external_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedimage',
            name='small_image',
            field=models.ImageField(default='none', upload_to=app_saver.models.get_image_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unsplashdailyload',
            name='last_load_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
